### ISSUE TITLE
JWS playbook/configuration to be used as examples.

### ISSUE THREAD

**Issue by defeatedbylife** [ansible-middleware/jws#161]
##### SUMMARY

We have a minimal Tomcat example. We should have more example playbooks that people can easily try out.

##### ISSUE TYPE
 - Feature Idea

**Comment by csutherl** [comment]
We can target this for our next release and add a few different sample `vars.yml` files to the playbooks dir.

**Comment by rpelisse** [comment]
we could add a few files like vars_https.yml, vars_tomcat_vault.yml or vars_ajp indeed, but if we do we should also ensure that those are used and run by jws-dot. 

(in fact, it will probably boil down to removing vars files from jws-dot's molecule scenario to move them to upstream's playbooks/)

**Comment by rpelisse** [comment]
As discussed with @csutherl , I'm closing this issue, as we'll move this discussion somewhere more appropriate.
