### ISSUE TITLE
Organize jws role documentation

### ISSUE THREAD

**Issue by defeatedbylife** [ansible-middleware/jws#162]
##### SUMMARY

The jws role documentation is concentrated and not user friendly. Variables are group together in one big table which makes it hard to figure out with ones to use or which ones I want to change to use some specific functionality.

##### ISSUE TYPE
 - Bug Report

##### COLLECTION VERSION

```
1.1.1
```

**Comment by csutherl** [comment]
We could break them up into tables per feature; would that be helpful? I.e. group all of the modcluster settings together in a table similar to how we present scenarios.

**Comment by csutherl** [comment]
@defeatedbylife thoughts on #171 ?

**Comment by rpelisse** [comment]
As discussed with @csutherl , I'm closing this issue. We'll move this discussion in more appropriate place about docs.
