### ISSUE TITLE
groupinstall of jws rpm installation does not execute

### ISSUE THREAD

**Issue by sabre1041** [ansible-middleware/jws#174]
##### SUMMARY
Currently, the `groupinstall` RPM installation method does not execute. Partial functionality of installing JWS in certain conditions is still successful when also installing the `jws5-tomcat-vault` package beforehand.

The issue has been identified to be caused by an incorrect check when determining the dnf command that should be executed.

##### ISSUE TYPE
 - Bug Report

##### ANSIBLE VERSION
```
all versions
```

##### COLLECTION VERSION
```
1.1.1
```

##### STEPS TO REPRODUCE
Set the following inventory variable to trigger RPM based installation
```yaml
tomcat_install_method: rpm
```

##### EXPECTED RESULTS
RPM groupinstall executes successfully

##### ACTUAL RESULTS

groupinstall installation does not occur

```

```

**Comment by rpelisse** [comment]
Fixed by [PR173](https://github.com/ansible-middleware/jws/pull/173).
