### ISSUE TITLE
Fix inconsistencies in Ansible versions

### ISSUE THREAD

**Issue by jajik** [ansible-middleware/jws#283]
Currently, there are several conflicting messages.

* From the README, one might think Ansible 2.14 is supported
* In this [commit](https://github.com/ansible-middleware/jws/commit/d4a91d9f502e1b34d2a024d0e25d3d052977b3a2) the required version got updated to 2.16
* Github Actions run workflows with Ansible 2.15 which leads to warnings about an unsupported version...

**Comment by jajik** [comment]
>     * Github Actions run workflows with Ansible 2.15 which leads to warnings about an unsupported version...

e.g., 
![image](https://github.com/user-attachments/assets/51fbfe27-2fb2-4498-bd5a-30056fe7ed0e)

**Comment by rpelisse** [comment]
2.16 is definitely the new golden standard, however, I think 2.15 is still supported (at least on RHEL), but you are right, we should probably put that in a centralized variable (or have a handy script to update this consistently)

**Comment by rpelisse** [comment]
This duplicates this [internal issue](https://issues.redhat.com/browse/AMW-334), so for the sake of simplicity I'm closing as a duplicate.

**Comment by jajik** [comment]
@rpelisse I don't see any CI mention in the internal issue.

**Comment by rpelisse** [comment]
Not directly, but this will be dealt with there too. So better carry on the discussion over there.
